pages:
  - url: https://test.com # URL to monitor
    selector: .class-selector # DOM selector
    schedule: "* * * * *" # Run every minute
notify:
  email:
    address: smtp.gmail.com
    port: 587
    user: hello@hello.com
    password: password
    receivers:
      - me@myemai.com
  slack:
    token: token
    channel_id: id
