// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	crawl "github.com/ainsleyclark/stock-informer/crawl"
	mock "github.com/stretchr/testify/mock"
)

// Scraper is an autogenerated mock type for the Scraper type
type Scraper struct {
	mock.Mock
}

// Scrape provides a mock function with given fields: url
func (_m *Scraper) Scrape(url string) (*crawl.Content, error) {
	ret := _m.Called(url)

	var r0 *crawl.Content
	if rf, ok := ret.Get(0).(func(string) *crawl.Content); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crawl.Content)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewScraper interface {
	mock.TestingT
	Cleanup(func())
}

// NewScraper creates a new instance of Scraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScraper(t mockConstructorTestingTNewScraper) *Scraper {
	mock := &Scraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
