// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	httputil "github.com/ainsleyclark/stock-informer/httputil"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Do provides a mock function with given fields: URL, method
func (_m *Client) Do(URL string, method string) (*httputil.Response, error) {
	ret := _m.Called(URL, method)

	var r0 *httputil.Response
	if rf, ok := ret.Get(0).(func(string, string) *httputil.Response); ok {
		r0 = rf(URL, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httputil.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(URL, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
